### ISSUE TITLE
User can search for food

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/ajax-project#1]
## ⚙️ Feature
> ##### What capability will users have when this feature is merged?

User can search for food.

## 📐 Functionality
> ##### A description of how the application will work from the perspective of the user.

Create a responsive search bar that allows users to search for food.

## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-14 at 9 54 55 AM](https://user-images.githubusercontent.com/113560956/201731854-915b4c31-a543-4e11-a3e7-9149d51733cc.png)
![Screen Shot 2022-11-14 at 9 55 09 AM](https://user-images.githubusercontent.com/113560956/201731919-a8fe27f9-7cb1-47b2-bfc2-c1f94fda6212.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML skeleton based on wireframe with div[data-view="search-form"].
- [x] Style HTML skeleton with CSS to match wireframe.
- [x] Add form element with input type "search" for search bar.
- [x] Position a magnifying glass icon to the left within search bar.
- [x] Position a X icon to the right within search bar.
- [x] Remove inherent X style.
- [x] Add 'click' event listener to X icon to clear out search bar.
- [x] Add CSS media query for responsive mobile layout to match mobile wireframe.
- [x] Add appropriate JavaScript code to listen to text input from search bar.
- [x] Add a 'submit' event listener for the form that invokes function to:
  - [x]  Create new XMLHttpRequest() Object.
  - [x]  Open a GET request to Edamam Food Database API concatenated with the input value of the search bar.
  - [x]  sets a response type of 'json'
  - [x]  sends request to server
  - [x]  Console log status and response to make sure correct data is being pulled.
  - [x] Reset form.
- [x]  Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
