### ISSUE TITLE
User can view more search results

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/ajax-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view more search results

Upon clicking 'view more' button, more search results are loaded from API.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-11-18 at 2 18 55 PM](https://user-images.githubusercontent.com/113560956/202812514-ae4a8345-fef4-486f-923e-35226649a70f.png)
![Screen Shot 2022-11-18 at 2 19 18 PM](https://user-images.githubusercontent.com/113560956/202812567-e1ccea85-b841-4a47-8d32-b8c5cadf00a7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make sure nav bar is in a position: fixed so that when scrolling down the page, it remains at top of viewport.
- [x] Create a new link/button for 'View More'.
  - [x] When button is 'hovered' over, change opacity.
  - [x] When button is 'active' change color.
- [x] Create addEventListener to listen to 'click' event for 'View More' button.
- [x] 'click' event should invoke the following
  - [x] invoke the function that creates a HTTP Request for the "next page" of the API.
  - [x] invoke the renderResult function
  - [x] append results to the DOM tree 
- [x] Make sure that results are appended to the end of the previous search result, rather than replacing them. 
- [x] Make sure the 'View More' button stays at the bottom of the results. 
- [x] Add a loader while getting more results.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
