### ISSUE TITLE
User can autocomplete search using typeahead

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/ajax-project#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can autocomplete search using typeahead

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon entering search input, list of autocomplete suggestions appear.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="194" alt="Screen Shot 2022-11-19 at 1 11 26 AM" src="https://user-images.githubusercontent.com/113560956/202843714-becce669-1c6b-4579-92a2-0c2c6247b226.png">

<img width="578" alt="Screen Shot 2022-11-19 at 1 12 44 AM" src="https://user-images.githubusercontent.com/113560956/202843770-7c3b4c35-5f1c-4a39-8e2e-ee7d9161efb2.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a 'ul' element to HTML under search bar.
- [x] Add dummy data to children 'li' elements and style with CSS to match wireframe.
- [x] Create an addEventListener to listen for 'input' for the search bar value.
- [x] Console Log to make sure value of input is correctly recorded.
- [x] Create HTTP Request function for Edamam autocomplete API. Within function:
  - [x] Add a debounce with setTimeout() for each 300-400ms to prevent a request from sending every character typed. 
  - [x] Console log response from request to ensure correct data is returned.
  - [x] For each response, create 'li' element.
  - [x] Append 'li' element to parent 'ul' element.
  - [x] Clearing search and searching again should clear previous 'li' elements.
- [x] Make sure selecting typeahead suggestion replaces search input value.
- [x] Ensure that when input is cleared out, no suggestions appear and styling is consistent with wireframe.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
