### ISSUE TITLE
User can view a list of matching food

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of matching food

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon submitting search form, a search results page with matching food items is displayed.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-14 at 2 56 39 PM](https://user-images.githubusercontent.com/113560956/201785429-facfc89c-bdc3-498b-bb83-091e98e08373.png)
![Screen Shot 2022-11-14 at 2 56 54 PM](https://user-images.githubusercontent.com/113560956/201785436-b96358cd-731c-421a-846c-99ed43889e13.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling div[data-view="results-page"] to the HTML.
- [x] Add a div with class row to the div[data-view="results-page"] element.
- [x] Add some dummy search results to the row to style them to match wireframe.
- [x] Check that results look good on both mobile and desktop screens.
- [x] Add onto the getFoodData function
  - [x] loop through the response of the request to create a DOM tree for each result that includes the image and food label.
  - [x] append to the row class above.
- [x] Remove the dummy search results.
- [x] Add condition for if there are no results.
- [x] Ensure that clicking on a result will change it's CSS style to reflect wireframe.
- [x] Ensure that submitting a search automatically shows the 'results page' view without reloading the page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
