### ISSUE TITLE
User can select and view macros nutritional facts about the item and save to a list of favorite items

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select and view macros nutritional facts about the item and save to a list of favorite items

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon selecting an item from the search result, details page shows up for that item. Upon clicking on empty heart icon, item is saved to a favorites list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-15 at 11 24 14 AM](https://user-images.githubusercontent.com/113560956/202007612-cf20b387-e4c8-4573-9ca1-7c1c1cbe6e82.png)
![Screen Shot 2022-11-15 at 11 25 10 AM](https://user-images.githubusercontent.com/113560956/202007762-996ccc69-167f-49f1-ba53-ca1a2c3cc49d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling div[data-view="details-page"] to HTML.
- [x] Add a HTML skeleton with some dummy data for details page to reflect wireframe.
- [x] Add JavaScript to add a data-search-id to each rendered div for search results (should match indices of response object).
- [x] Add JavaScript for when clicking on a search result item it pulls correct data from response object and injects data into details page HTML.
- [x] Add JavaScript for when clicking on a search result item, it view swaps to the details page without reloading page.
- [x] Set up local storage to save object if user clicks on empty heart icon.
  - [x] Code for when clicking on empty heart icon, switches to full heart icon
  - [x] Clicking on empty heart icon will create object and push it to local storage
  - [x] Object should be rendered and appended to favorites page (feature 4)
  - [x] Switching to full heart icon should also create a true boolean
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
