### ISSUE TITLE
User can view a list of favorited items

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of favorited items 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon clicking top right heart icon, user is taken to their favorites page and is able to view all favorited items.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-11-16 at 10 25 48 AM](https://user-images.githubusercontent.com/113560956/202262582-d8000609-35f6-4c4e-b56a-f58768532402.png)
![Screen Shot 2022-11-16 at 10 26 09 AM](https://user-images.githubusercontent.com/113560956/202262630-d86625f0-f2cf-4bec-b4ea-a69b1b83fb9c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add sibling div[data-view="favorites-page"] to HTML
- [x] DOM query top right heart icon and add 'click' add event listener to view swap to favorites page
- [x] Make sure favorited items are rendered correctly on favorites page when favoriting an item
- [x] Make sure when going to another details page, heart icon is empty again.
- [x] Make sure all favorited items are stored correctly in local storage
- [x] Make sure when reloading page, it stays on favorited page
- [x] Make sure when reloading page, items from local storage are rendered back onto favorited page.
- [x] Make sure that clicking on item from favorite page leads back to details page
- [x] Make sure that when clicking on item from favorite page, on details page, heart is still full.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
