### ISSUE TITLE
User can delete items off of favorited items

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete items off of favorited items.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon clicking on a full heart icon, item is deleted off of favorited list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="406" alt="Screen Shot 2022-11-16 at 3 24 50 PM" src="https://user-images.githubusercontent.com/113560956/202316514-04b4a5ae-455a-408c-b66d-38c72f4cc168.png">

<img width="711" alt="Screen Shot 2022-11-16 at 3 24 33 PM" src="https://user-images.githubusercontent.com/113560956/202316479-d82a993e-756e-4989-bbda-3bae3cceda66.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make sure clicking on a full heart icon, switches icon to empty heart icon.
- [x] Add JavaScript code and condition that if a full heart icon is clicked, the following happens:
  - [x] removes correct item from local storage.
  - [x] removes correct item from DOM tree.
- [x] Make sure that when clicking on favorites page, the item no longer shows up.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
